version: '3.8'

services:
  mysql:
    image: mysql:8.0.32
    container_name: docker-mysql
    restart: always
    environment:
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:rw
      - mysql-data:/var/lib/mysql:rw

  adminer:
    image: adminer
    container_name: docker-adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    mysql-data:
